// <auto-generated />
namespace UFESManager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Student_StudentId_RemoveGeneratedNone : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Student_StudentId_RemoveGeneratedNone));
        
        string IMigrationMetadata.Id
        {
            get { return "202109152118292_Student_StudentId_RemoveGeneratedNone"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
